### ISSUE TITLE
Toolbar icon window name overlay issue

### ISSUE THREAD

**Issue by BenceSzalai** [l10nelw/winger#14]
Hi! I'm glad to see the plug-in being improved! Thank you for working on this great addition! It is really a game changer for using the browser windows effectively!

However in the new v2 the window name is overlaid on the toolbar icon, but in fact the icon size is too small to accommodate window name, so it is a truncated stub only. It does not add too much benefit in my case, but I know some others may like it, but I preferred the old, more minimalistic look. Now the icon is almost invisible, but certainly unrecognisable unless someone knows what is there already...

This is an example of my toolbar with a test window named MyWindow.
![immagine](https://user-images.githubusercontent.com/14061916/214147646-a0d7e4cb-b2bb-4099-a856-38a8bae920c2.png)

Seeing "MyV" instead of the top part of the icon is not particularly useful. What do you think?

**Comment by l10nelw** [comment]
Thanks Bence, that's fair. Option to toggle the icon badge on/off will be back in the next version.

Perhaps the icon should be improved to have a more recognisable lower half as well? I'll have to figure that one out..

**Comment by l10nelw** [comment]
2.0.1 update:
- The badge can be toggled off
- Winger icon slightly more distinguishable with badge on
