### ISSUE TITLE
Unstashing folders no longer works

### ISSUE THREAD

**Issue by mkalinski** [l10nelw/winger#15]
### To reproduce

1. Have a folder containing any number of bookmarks.
2. Right click on the folder and select the "Unstash" command from the menu.

### What happens

1. A new window is opened.
2. The name of the new window is "(no name)".
3. No bookmarks are opened in the new window.
4. The unstashed folder is not removed (regardless if using shift-click or normal click).

### What should happen (and did in the previous version of Winger)

1. A new window is opened.
2. The name of the window is set to the name of the unstashed folder.
3. The bookmarks from the unstashed folder are opened in the new window.
4. The unstashed folder is removed (if not using shift-click).

---

Unstashing single bookmarks (not folders) works as described in help, for what it's worth.

**Comment by l10nelw** [comment]
I'm unable to reproduce the issue, @mkalinski. Is it possible to record a video of this bug?

**Comment by mkalinski** [comment]
Sure.

This is recorded for a completely new profile (only Winger installed) on a Fedora 37 system. The tab that opens is the default homepage (if it was set to something different, that would have been opened instead).

[Screencast from 2023-01-30.webm](https://user-images.githubusercontent.com/959502/215551498-994d5267-a033-4cc4-a734-02ac0655d912.webm)

**Comment by l10nelw** [comment]
Could you open `about:devtools-toolbox?id=winman%40lionelw&type=extension` and then do an unstash? Please share what you see.

**Comment by mkalinski** [comment]
I've already checked the extension debug window before, and unfortunately it's just nothing.

[Screencast from 2023-02-05.webm](https://user-images.githubusercontent.com/959502/216826186-52f1674f-ba09-45c6-8c13-72abb4792528.webm)

**Comment by l10nelw** [comment]
Did it work before in earlier Winger versions?

**Comment by mkalinski** [comment]
Yep, it worked without problem in every Winger version before 2.0 (hence I named this issue "no longer works").

**Comment by l10nelw** [comment]
Silly me. Anyhow, I need more time to investigate why it works in Windows and MacOS at least but not your system.

**Comment by mkalinski** [comment]
I don't know how much it'll help, but the problem occurs in the same way under both Wayland and Xorg. So it's at least not a Wayland-specific Firefox bug.

My desktop environment is Gnome.

These details shouldn't matter probably, but since this extension creates OS windows, maybe there are some Firefox on Linux bugs related to that. The unstashing process clearly stops silently after creating the window in:

https://github.com/l10nelw/winger/blob/3a8d6aeaba4ed4f9b5b93d1a7019c5f729054d54/background/stash.js#L130

but before the logging in:

https://github.com/l10nelw/winger/blob/3a8d6aeaba4ed4f9b5b93d1a7019c5f729054d54/background/stash.js#L155

if `onWindowCreated` is even called.

**Comment by mlncn** [comment]
Confirming this problem in Firefox 109.0 on Debian GNU/Linux bookworm/sid Gnome 43.3 Wayland.

**Comment by FFdhorkin** [comment]
Seems to be happening on 111.0b8 (Windows 11 64-bit), as well. It opens a new window, but only the default tab opens, no restored tabs

**Comment by l10nelw** [comment]
The latest version v2.1.0 is a significant rework that should resolve this issue. @mkalinski can you confirm?

**Comment by mkalinski** [comment]
Looks like it works for me now, thanks a lot. :+1:

**Comment by l10nelw** [comment]
Thanks @mkalinski, I'll consider this resolved. I'm pretty confident since I've removed the point of failure entirely.

**Comment by mlncn** [comment]
Working for me also, this is awesome!
