### ISSUE TITLE
Submitting new window name after /edit (or /name) no longer works

### ISSUE THREAD

**Issue by mkalinski** [l10nelw/winger#16]
### To reproduce

1. Click on the Winger extension button.
2. Type `/edit` or `/name` and press enter.
3. The prompt to rename the window opens.
4. Type any name and press enter.

### What happens

Nothing. The new name is not submitted, the prompt remains open and active, but the edit cannot be completed in any way other than exiting out from the extension menu (which cancels the edit).

### What should happen (and did in the previous version of Winger)

The name is submitted as the new name of the window, and we go back to the normal search box that's active when the extension menu is opened.

---

Note that the expected behaviour happens when the name editing prompt is activated by clicking on the active window's name. It's only when it's accessed by typing the slash command that it doesn't work.

**Comment by l10nelw** [comment]
When entering edit mode via `/edit` or `/name`, the omnibox stays targeted, so you need to press Up/Down keys or click to target the row you want. Typing in the omnibox performs filtering as usual, which now also works in edit mode.

It's actually easier to rename the _current_ window now; from the omnibox you just press Up then Enter to activate edit mode (current window targeted).

Thank you for sharing your issue, I will look into how to design things to be much clearer, and clarify in the help as well.

**Comment by mkalinski** [comment]
Okay. I admit, I didn't quite understand what was meant when the docs mentioned "filtering in edit mode", but I didn't really care, since I couldn't think of a use case I would have for this.

I think the tooltip is terse to the point of being slightly misleading.

![image](https://user-images.githubusercontent.com/959502/215552478-42728265-74c6-408a-9ab4-b340c884108a.png)

Yes, it says "on a name", but there's no indication I could move to a name. And from my point of view, I've just typed a name.

But the core of the issue probably is that doing the same thing that worked in version 1.x doesn't anymore.

Perhaps it would be good to display clarification on the tooltip when pressing enter in the omnibox (since it seems to do nothing currently)?

**Comment by l10nelw** [comment]
Yes a better message in the status bar for this condition is in order. Thanks.

>I couldn't think of a use case I would have for this

If you have a large number of windows, when filtering would be helpful to find the window you want.

**Comment by l10nelw** [comment]
Relevant 2.0.1 updates for edit mode:
- New instructional status text for when no name field is focused while in edit mode
- In edit mode, all name fields have the same field background colour, leaving no doubt that edit mode is active and that they are all editable
