### ISSUE TITLE
Named windows:  Is it possible to hide current tab name in Window Menu?

### ISSUE THREAD

**Issue by jclark-dot-org** [l10nelw/winger#17]
I name all my windows.  I tend to have many windows, as I keep one per client.  I find it very handy to jump to the right window via the Window menu in the FF toolbar.  Currently, I see each window listed as `<WindowName> - <TabName>`, like:

> ExampleCo - Inbox (196) - jason@example.co - ExampleCo Mail
> Dev Documentation - Apex Developer Gude | Salesforce Developers
> Personal - New Issue - l10nelw/winger
> ClientCo - Login
> etc...

When I'm using the Window Menu, I don't care what tab a window is on; I just need to scan a list of client names (and a few special cases, like Dev Docs and Personal).  In other words, I'd like to see only the Window Name that I assigned, but NOT the current tab name.  Is there any way to change this behavior in the Window Menu?

**Comment by l10nelw** [comment]
It's not possible to modify an entire window title; only the title preface, and I suppose indirectly via modifying the active tab title, which might require an extra permission.

Would it help to display the window name in a different, user-defined format? For example:

`[windowName] tabName`
> [ExampleCo] Inbox (196) - [jason@example.co](mailto:jason@example.co) - ExampleCo Mail
> [Dev Documentation] Apex Developer Gude | Salesforce Developers
> [Personal] New Issue - l10nelw/winger
> [ClientCo] Login

`windowName ≫ tabName`
> ExampleCo ≫ Inbox (196) - [jason@example.co](mailto:jason@example.co) - ExampleCo Mail
> Dev Documentation ≫ Apex Developer Gude | Salesforce Developers
> Personal ≫ New Issue - l10nelw/winger
> ClientCo ≫ Login

and so on.

**Comment by jclark-dot-org** [comment]
@l10nelw Thanks for the feedback.  I agree there's no need to modify the active tab title, I was hoping it could just be suppressed. 

I'm trying to switch from Chrome, where I used a (much more basic) plugin to rename windows, and I'm used to the Window menu (was the only option), but you make a great point about <kbd>F1</kbd> and the Winger omnibox.  I'm more of a keyboard guy than a mouse guy andway, so I'll see if I can start training myself to use that.  Even using the mouse to select from the <kbd>F1</kbd> popup means that I see only window titles without tabs, so it's still a win.  I just need to retrain muscle memory.

I'll close this since the original request isn't technically possible, and since I think using <kbd>F1</kbd> is better than reformatting the window menu.  One thing that would be nice (but that I can totally live without) would be fuzzy search when typing window names.  So if I have tabs "Client" and "Client Dev", I could type <kbd>c</kbd><kbd>l</kbd><kbd>d</kbd> to match "Client Dev".

**Comment by l10nelw** [comment]
Glad to help!

Fuzzy search has been in my wishlist, so I'll take your vote for it.
