### ISSUE TITLE
[Req] Automatically Minimize Previous Window

### ISSUE THREAD

**Issue by TooSpooky** [l10nelw/winger#18]
Hello,

Apologies if this is already possible, but at times I use a window manager called Komorebi which automatically tiles open windows. Would it be possible to make it so the previous window you're coming from is automatically minimized so it would be a seamless switch when using a tiling manager, instead of having two windows side by side and having to close one?

Of course as an option and potentially if you have the option selected you could say shift click the window you want and it'll open as normal without minimizing the previous as well. 

Thanks for your time and take care!

**Comment by l10nelw** [comment]
I have been thinking quite a bit about this, and I believe the solution should be a dedicated auto-minimizer addon. I could take a stab at it, if you haven't already found one or decided to try building it yourself. What do you think?

**Comment by TooSpooky** [comment]
Interesting, I think that could work. Sadly I don’t have the knowledge to make one myself haha, but would truly appreciate it if you took a crack at it

thanks for thinking about it!

**Comment by l10nelw** [comment]
I've done it: https://addons.mozilla.org/en-US/firefox/addon/auto-minimize/

Probably rough around the edges. If you have any issues please head on to https://github.com/l10nelw/auto-minimize/issues

**Comment by l10nelw** [comment]
@TooSpooky How is it?

**Comment by TooSpooky** [comment]
Oh wow, I missed that notification. Im going to give this a shot today then and get back to you, sweet. Thanks!

**Comment by TooSpooky** [comment]
Seems to work good on quick testing, only with one issue. I use two windows by default, on my left monitor my browsing/work window and on my right monitor videos/content/etc. So with 2 windows before auto minimize selected, my right window sometimes is the one to minimize instead of my left. Would there be a way to implement prioritization? I.E. The last focused window is the one minimized and/or clicking an icon in the extension bar turns off auto minimize for that window? 

Thanks a ton by the way, apologies I missed this. Very useful. @l10nelw
