### ISSUE TITLE
Windows lost and names lost and all non-pinned tabs lost

### ISSUE THREAD

**Issue by SweRavn** [l10nelw/winger#2]
After a Windows reboot. Really sad. Not sure what else to report. Parts of this might be Ff and parts winman. Let me know if I can add any information.

**Comment by l10nelw** [comment]
Yikes that's terrible, @SweRavn. I haven't encountered anything like that so far on my Linux Mint and Windows. Has it happened more than once?

**Comment by SweRavn** [comment]
Nope, only once. Flawless after that.

**Comment by l10nelw** [comment]
Good to hear. I can't think of any way the extension could cause the problem since the only data it stores and manages are window names, and nothing about tabs. I'll close this, cheers

**Comment by SweRavn** [comment]
Hi, now this happened again and the window names were again lost. I turn off the computer, and Ff was not turned off. So, if winman stores window names, that is lost. All non-pinned tabs are lost and since I did not have any pinned tabs in one window, that window was lost entirely. If I chose "Recover last session" from the menu, the tabs and windows return, but not the window names.

**Comment by l10nelw** [comment]
What other extensions are you using?

**Comment by BenceSzalai** [comment]
So, is there a compatibility issue with Tree Tab Style? I've been using Tree Tab Style for a while and about to start using Winger now.

**Comment by l10nelw** [comment]
Hi @BenceSzalai, I haven't encountered any problems with TST and Winger together so far. While I'm not really a TST user*, at least one [Winger reviewer who also uses TST](https://addons.mozilla.org/en-US/firefox/addon/winger/reviews/1637576/) seems quite happy. If you want to be safe, I suggest you install an extension that periodically backs up your tabs, such as Tab Session Manager.

* Personally, to get a vertical list of tabs, I simply use the native "list all tabs" button (which I do frequently). Keyboard shortcut: Ctrl-Shift-Tab. If the button only appears when your tab strip overflows, you can use a [userChrome.css](https://www.userchrome.org/how-create-userchrome-css.html) hack to [make it always visible](https://old.reddit.com/r/FirefoxCSS/comments/8uz9d1/show_list_all_tabs_button_always/).

**Comment by SweRavn** [comment]
I still have this problem. When Ff is restarted a random subset of my windows forget their names. Sometimes it is all of them, somethings just 1 or 2. I cannot relate it to any other extension. Also, since I reported the issue, I have reinstalled Windows completely, and the issue is still there. I have not lost any tabs this time, it is only then window's names that are lost.

**Comment by l10nelw** [comment]
Sorry, I can only guess wildly at this point. Is there something messing with your browser's restore-last-session setting? Is it a hardware issue? Try migrating to another computer if you can.
