### ISSUE TITLE
New minimized window group header would cover the first window list item if all other windows were minimized

### ISSUE THREAD

**Issue by mikelei8291** [l10nelw/winger#23]
## Description

As you can see from the screenshot below, if all my other windows than the current one were minimized, then if I scroll down and then up the list, the first window item would be covered by the "Minimized" group header. The list is scrolled all the way up and cannot be scrolled anymore.

Also, the scrolling seems to have a "smoothness" effect applied that I don't really like. It feels unnatural and not responsive. I hope it can be revert back to the native scrolling behaviour of the browser if it had been modified in any way.

Thank you for the new update! The extension is very helpful to me!

## Screenshot

![Screenshot](https://github.com/l10nelw/winger/assets/9620335/98100df1-e0a2-45cc-97f3-51c6939b36d1)

**Comment by mikelei8291** [comment]
Also it looks different in private windows:

![Screenshot](https://github.com/l10nelw/winger/assets/9620335/bfdc9b1f-0ccf-4b2b-ac31-b7b6315686f3)

**Comment by l10nelw** [comment]
What OS and browser version are you using?

**Comment by mikelei8291** [comment]
OS: Windows 10 (ver. 1709)
Browser: Firefox 114.0b9

**Comment by l10nelw** [comment]
By scroll, you mean by keyboard right? I am able to reproduce the issue via keyboard navigation. Thanks for reporting. A fix is on the way.

I can't reproduce your second issue though (private window). Is it still happening for you?

**Comment by mikelei8291** [comment]
Thanks for your reply. However, I was scrolling using my mouse wheel, but I can confirm that using keyboard navigation also has the issue.

I updated to Firefox 115.0b9 and the private window issue was resolved.

**Comment by l10nelw** [comment]
The patch has been released (v2.3.1)

**Comment by mikelei8291** [comment]
Thanks for the fix! I can confirm that the issue has been fixed after updating to v2.3.1.

I do have another issue with the scrolling though. When scrolling using the mouse wheel, the scrolling is always lagging behind the wheel movement. I think it is due to the implementation of keeping the selected window item at the center of the list, so you'd have to attach event listeners to handle the scroll of the list. It is fine when navigating the list using arrow keys, but it feels really laggy when scrolling using the mouse wheel. Could this be fixed in any way? If not, then no worries, and I'm just going to get used to it.

**Comment by l10nelw** [comment]
I'll have to get a mouse to see this issue for myself 😆. Will keep you posted.

**Comment by mikelei8291** [comment]
Thanks a lot for your help!

Glad to know that there's nothing done to affect mouse scrolling. This is interesting... I'll try to look into the code to see if I could find anything.
