### ISSUE TITLE
[Request] new stash location: "Tab Stash"

### ISSUE THREAD

**Issue by AeliusSaionji** [l10nelw/winger#24]
Some basic 'integration' with the Tab Stash extension could be achieved by simply stashing where it stashes. Which is "any folder named `Tab Stash`"

That also could satisfy request #5 for a sidebar, although Tab Stash might need to modify its context menu to be able to access the unstash window button.

**Comment by l10nelw** [comment]
Hi @AeliusSaionji, you can now customize the stash home subfolder name in the latest version 2.4.0. I believe you should set the root to "Other Bookmarks" and subfolder name to "Tab Stash" and you're good!
