### ISSUE TITLE
[Request] option to completely replace window name

### ISSUE THREAD

**Issue by supersaiyansubtlety** [l10nelw/winger#28]
Currently window names appear to be `<Winger name> - <original window name>`; it'd be nice to have an option for it to just be `<Winger name>`.

If #27 is implemented, it'd also be nice to have an option for window names to be `<shortened Winger name>`.

Use case: I use [TidyTabs](https://www.nurgo-software.com/products/tidytabs) and the default name for Tidy tabs for Firefox windows is the window name. Currently I manually rename them to remove the `<original window name>` part.

**Comment by l10nelw** [comment]
It's technically `<title preface><current tab title>`. Addons may only add a title preface. Meanwhile the tab title, really the document title, cannot be completely cleared -- if the document's title is blank, the document's url is shown as the tab title instead.

So I don't think it's possible to modify a window title in the manner you require, sorry.

**Comment by supersaiyansubtlety** [comment]
Ah ok
