### ISSUE TITLE
Question: Is it possible to set one of the windows as the default to open links from other applications?

### ISSUE THREAD

**Issue by ultrablue** [l10nelw/winger#29]
Hi:

Is it possible to set one of the Windows as the default to open links from other apps in?
For example, if there's a link in an email, I would like to always open in a specific window.

Thanks!

**Comment by l10nelw** [comment]
Not exactly possible, the window that opens the links is always the last focused one, I believe.

A solution to this would be an addon that detects the new tabs and auto-moves them to the desired window. I don't know of any at the moment, unfortunately. I'd like to try creating one if I had some free time. Sorry, I would not like to implement this as a Winger feature, as I feel like it's a whole different thing that's worth being its own addon.

**Comment by ultrablue** [comment]
Cool.
Thanks for getting back.
