### ISSUE TITLE
Incompatible with other addons that are using titlePreface

### ISSUE THREAD

**Issue by Lej77** [l10nelw/winger#31]
Even if a window name is never specified this addon will [still update the titlePreface](https://github.com/l10nelw/winger/blob/228900dfee2549f8df555c031d0099d85b7b3857/background/chrome.js#L19C48-L19C48), clearing any titlePreface specified by other addons. It would be nice if this behavior could be disabled so that it is possible to use other addons for the title preface. I am using [Tab Count in Window Title](https://addons.mozilla.org/firefox/addon/tab-count-in-window-title), but there are a lot of other addons that also make use of the titlePreface. For example [Sidebery](https://addons.mozilla.org/firefox/addon/sidebery) allows setting it when its sidebar is visible to [control CSS inside `userChrome.css`](https://github.com/mbnuqw/sidebery/wiki/Firefox-Styles-Snippets-(via-userChrome.css)#dynamic-native-tabs).

While an "enable window title" checkbox on the settings page (that is checked by default) would be enough to fix this I think you should also consider making the `sessions` permission optional. I did this for my `Tab Count in Window Title` addon by making the permission request the [first time a user tried to name a window](https://github.com/Lej77/tab-count-in-window-title/blob/3d8e7e6c1309d21521791d27efccb96ed87010d4/popup/popup.js#L142-L158) and that seems quite intuitive to me. Though thinking about this some more, it is possible that a user would want to name a window without actually changing the window title. So having both a checkbox and an optional permission could make sense.

**Comment by frasty** [comment]
Probably related to this issue, I use [window titler](https://github.com/tpamula/webextension-window-titler) and winger actually clears the window titles I previously specified with window titler. It would be nice if winger could inherit the title from window titler and other addons that make use of titlePreface.

**Comment by l10nelw** [comment]
Thank you for this. I have been planning to make window naming optional for quite some time to accommodate other window titlers. I'll make this a priority.

**Comment by Lej77** [comment]
This issue seems to be fixed in version `2.5.0` of the extension, see issue #40.

**Comment by l10nelw** [comment]
https://github.com/l10nelw/winger/wiki/Using-Winger-with-another-window-naming-extension
