### ISSUE TITLE
[Feature Request] Configurable delay before unloading tabs in minimized windows

### ISSUE THREAD

**Issue by mikelei8291** [l10nelw/winger#32]
The unloading tabs in minimized windows feature is great, but I've had some occasions when I accidentally clicked the minimize button and then found that all tabs other than the active one was unloaded.

Therefore, I would suggest adding a configurable delay in the settings and only unload tabs in minimized windows after the specified delay. Thank you.

**Comment by l10nelw** [comment]
Done v2.7.0
