### ISSUE TITLE
Stashing intermittently works

### ISSUE THREAD

**Issue by loopernow** [l10nelw/winger#39]
Edit #2 
After removing and reinstalling the extension to try to narrow down what behavior gets stashing to work, had a heck of a time getting it to work again.

Manually typing in names of folders to use, created those folders but no bookmarks were stashed within them.

After deleting all stash folders and then selecting a folder again, the folder was created and I was able to stash bookmarks within it. However, the next time I ran the /stash command, no bookmarks were stashed.

---

Edit: Just changing the folder in the drop-down menu does not solve the issue. I believe what actually causes the extension to start saving the bookmarks is to click in the folder location box so that the cursor is there, and then press Enter.

---

I thought stashing was not working, but figured out what the actual bug is: Stashing does not save bookmarks unless the folder location is changed at least once in Winger's options.

To reproduce:
1. Install winger
2. Enable stashing in Options
3. Give the necessary permissions in Firefox
4. Stash some tabs

At this point, you will have a Stashed Windows folder in your Bookmarks Toolbar folder, but no folders or bookmarks within.

Workaround to get stashing to work:

1. I don't know if it's necessary to close and reopen Firefox at this point, but it doesn't hurt.
2. Change the folder location for stashed tabs to either Bookmarks Menu or Other Bookmarks.
3. Stash some tabs
4. (Optional) Change the folder location in Options back to the Bookmarks Toolbar

I'm on Windows 10.

**Comment by l10nelw** [comment]
Thank you @loopernow for the thorough bug hunt! Fixed in the latest update.
