### ISSUE TITLE
What's new in 2.5.0?

### ISSUE THREAD

**Issue by jclark-dot-org** [l10nelw/winger#40]
I just received an automatic update this morning ("Last updated v2.5.0 (6 Mar 2024)"), but the release note don't list any changes or fixes for this version, and there are no commits to any branch that I can see for the past 2 months.  What has changed?

**Comment by unchris** [comment]
I noticed this as well, no code changes here as evidence but somehow the plugin grew in size from `78.69 KB` to `80.28 KB`. 

I'm happy to be a tinfoil hatter type and be proven wrong but I reverted to 4.2.2 by downloading it from https://addons.mozilla.org/en-US/firefox/addon/winger/versions/ and turned off automatic updates for now. 

There are too many cases of authors having their plugins hijacked on plugin/package stores to take a chance these days 😅

**Comment by Lej77** [comment]
The `.xpi` files that the extension is downloaded as are basically just `.zip` files and so they can be unpakced to view the source code. I downloaded `v2.4.4` and `v2.5.0` from <https://addons.mozilla.org/en-US/firefox/addon/winger/versions/> and copied the code from them into a fork of this github repo. You can see the changes at:

[v2.5.0 from https://addons.mozilla.org/firefox/downloads/file/4246319… · Lej77/winger@80fc789](https://github.com/Lej77/winger/commit/80fc7891825bca8bb426590b5e5f7fa5809149de)

The [changes to the `options.html`](https://github.com/Lej77/winger/commit/80fc7891825bca8bb426590b5e5f7fa5809149de#diff-cfe614044d3abb280d27ac2d618f154c41f38f684e455dcf12693a63cf2a2194) page might be interesting to quickly see what new features are available. Seems to be some changes related to not setting a title preface for browser windows.

**Comment by jclark-dot-org** [comment]
@Lej77 Nice idea to post to a fork, thanks.  I was just reviewing the changes locally myself.  So far I haven't spotted anything suspicious.  Certainly looks like some planned changes, just without any change log.

**Comment by l10nelw** [comment]
Apologies everyone, I hadn't prepared the release notes when I submitted the update late last night and fell asleep. Will not do that again! Notes are on the way.
