### ISSUE TITLE
'Send to Window' contextual menu no longer seems to work after 2.6.0

### ISSUE THREAD

**Issue by EcksD33** [l10nelw/winger#42]
Greetings,

After the latest update, clicking on the contextual menu "Send to Window" > [Window name], nothing happens.
Same thing when holding shift while doing the same as above. This would should normally bring the window with the selected tab sent to it, but again, nothing happens.

I'm on Windows 10 using Firefox 124.0.2 (64-bit).

I do use other extensions which I guess could potentially clash with this one, among others I use the following extensions which manage tabs to some extent: Tab Stash, Auto Tab Discard, Duplicate Tabs Closer. I haven't tried disabling them to see if a clash was indeed the issue, sorry.

However, reverting to version 2.5.0 through the official Extensions site, I can confirm this feature still worked.

**Comment by l10nelw** [comment]
Sorry about this, a fix is coming. Thank you for reporting.
