### ISSUE TITLE
Can't find a way to add a Winger button to Firefox toolbar

### ISSUE THREAD

**Issue by Alucquere** [l10nelw/winger#43]
I'm a clueless Firefox 125.0.1/64-bit user who just moved to a new computer.

Right I right click on a tab page, I get "send tab to one of these windows) context menu.

But I can't find a button that I can use to add to the toolbar menu, and I can't figure out any way to open Winger in a sidebar or in a regular browser tab.

The problem with trying to use the context menu to send the current tab to another window is that it's hard to tell, from the context menu alone, which menu is which.

I tried messing around with the extensions folders in the Firefox profiles folder, but I don't understand all of this well enough to use anything in the extensions folders to fix the problem.

Winger continues to work well on the old computer, so, I don't think this is about a problem with permissions.

Anyhow, if this is all the result of a user error, I'm terribly sorry.

**Comment by l10nelw** [comment]
Have you done anything to make the tab bar to disappear? The Winger button might be on it.

Have you checked the Extensions button if Winger is listed in it?

**Comment by Alucquere** [comment]
- Most of my other extensions (example: FeedBro) show up. 

- Your extension isn't there when I click the toolbar overflow icon.

- It does show up in the "Manage Your Extensions" list, but I think it disappears. But: I don't think this is because of a security policy, because the extension and the button are working fine on the old computer. (Sorry; not sure what version of Firefox that one has; will look at that tomorrow.)

This is such a great app. I hope this is a bug and not something unfixable on my end.

**Comment by l10nelw** [comment]
You didn't do any hack to hide the tab bar, like some vertical tab extension users do? I ask because I set Winger button to initially land in the tab bar upon installation, which I know is a bit unusual. (I should probably change that in case it causes this kind of grief.)

**Comment by Alucquere** [comment]
- I don't think I've done anything weird to the toolbars; I have them all showing as much as I can. 

- The other computer has Firefox 124.0.2. Winger came off of that computer, too; maybe that's because of syncing, but maybe there is some new system security issue on my end.

- On the other hand: I have all sorts of extensions that seem to be working fine, so, it's strange that any security setting would affect just this extension and not my other extensions.

- In case this affects anything, I'm in the United States, using a computer with Windows 11 on it.
-

**Comment by l10nelw** [comment]
What happens when you press the shortcut to open the Winger popup panel (F1)?

Have you tried removing and re-adding Winger?

**Comment by Alucquere** [comment]
a. I've tried removing and re-adding Winger and haven't noticed that helping. I tried clicking F1 and think a shortcut conflict might have kept that from working.

b. I just tried changing the shortcut to Alt-W, and I got this:

![winger-sample](https://github.com/l10nelw/winger/assets/167366974/f3c50728-205d-4db5-83ee-ee5cd9ede5ff)

So, I see the windows list, but I don't believe that I get a way to name the windows or tell the windows apart. I can send a tab from one window to another.  Sorry I didn't realize I could do this before.

**Comment by l10nelw** [comment]
Interesting that you ended up with [this issue](https://github.com/l10nelw/winger/issues/41).

**Comment by Alucquere** [comment]
Thought: Say I use a shortcut to open the Winger window. The window doesn't have a name. Is there a shortcut I can then use to name the window? If I could just name the windows, then I'd have the functionality I need; I could live without a toolbar button.

**Comment by l10nelw** [comment]
Sorry, Winger window? You don't mean Winger's popup panel?

To name the current window you just open the panel, click on the top row to enter edit mode, then type a name and Enter. Does that not work?

It doesn't make sense to have a shortcut just for naming... You need an interface for inputting names, it might as well be the same panel.

**Comment by unbob** [comment]
I'm a new Winger user - just installed v2.6.2 on Firefox v125.0.1.

I'm not seeing a Winger button or Winger help button anywhere - where is it supposed to be?

Also, the Winger panel is truncated and incomplete and not being displayed correctly (see image below).

Is there a Winger "Getting Started" tutorial somewhere? Sure need it.

![Firefox Winger extension panel](https://github.com/l10nelw/winger/assets/83137978/d3285e12-1c7e-4678-af52-d8bb0c8f069f)

**Comment by Alucquere** [comment]
This problem got solved for my computer. I'm trying to figure out where I put the message about the solution; will try to post that here when I find it.

**Comment by unbob** [comment]
Thanks for the reply.
Winger seems to be working for me now - though I haven't tried bring/send.
Still no "Winger button" in sight anywhere - but guess not needed - instead just use keyboard shortcut to display Winger panel.
Also, "Send to WIndow" shows in tab context menu and that works A-OK.

**Comment by l10nelw** [comment]
@unbob You can enter **/** in the popup panel field (the omnibox) to summon help.

I'm still not sure how the Winger button could go missing, but please try these:

- Click on the Extensions button (🧩) or the More/Overflow button (>>). If you see the Winger button, right-click -> Pin to Toolbar / Unpin from Overflow Menu.
- Right-click on the toolbar -> Customize Toolbar. If you see the Winger button, you can drag it anywhere you want.

**Comment by l10nelw** [comment]
v2.7.0 drops what I suspect _might_ have contributed to the problem, but if this does solve it, it likely only solves it for fresh installations. Which means you can try it on a new profile, and then if all is well, you migrate and make it your new default profile.

Whatever this is, it's probably a Firefox bug; I don't have much control over this. I suggest requesting tech support at https://bugzilla.mozilla.org first, if you don't want to go through the above process yet.

**Comment by Alucquere** [comment]
For me it’s now working really well. I remember seeing somewhere that maybe a problem with a crashed tab messes up Winger. I have so many open tabs anything could be hiding in there. 

Sent from Yahoo Mail for iPhone


On Saturday, May 11, 2024, 10:53 PM, Lionel Wong ***@***.***> wrote:




v2.7.0 drops what I suspect might have contributed to the problem, but if this does solve it, it likely only solves it for fresh installations. Which means you can try it on a new profile, and then if all is well, you migrate and make it your new default profile.

Whatever this is, it's probably a Firefox bug; I don't have much control over this. I suggest requesting tech support at https://bugzilla.mozilla.org first, if you don't want to go through the above process yet.
