### ISSUE TITLE
[Request] configuration for how tall the Winger menu is

### ISSUE THREAD

**Issue by mcgrue** [l10nelw/winger#46]
![image](https://github.com/l10nelw/winger/assets/213483/36cd3110-8f13-46f2-b373-cec4fce45593)

I'd really like it if I could either have this go to the bottom of the open window (with a tasteful amount of bottom margin, ofc) or have it's vertical height otherwise be overriden by a fixed configuration value. 

I really value seeing as much as possible before scrolling

**Comment by l10nelw** [comment]
Turns out the maximum possible height for addon popups is about 33% more than it is currently. I'll increase it to that in the next version.

**Comment by mcgrue** [comment]
!!!

<3
